DISCORD_APP_ID: ENC[AES256_GCM,data:frQ63Yc9eXD7Vo5XT2Xv3Zi9BA==,iv:J6aAzmHWhQbI4a2JclzXwDKtIeessSkinpmGS79zS6k=,tag:NnGJD+M0xyJ3SlfBF5UjjQ==,type:int]
SUBSONIC_USERNAME: ENC[AES256_GCM,data:1e38BvrchH0=,iv:4t3clksFO2ewLENR1H768b8B2oyeOfYAD5xh97+ehss=,tag:w+WzYwoEYyvD+NwA786XyA==,type:str]
#ENC[AES256_GCM,data:jj5Va7W5CHyMXNZZpefU+T6o3h0/sy1U,iv:O+RAA1wJu0BsJIAqXOnwdWHmdxnrOwNwM4qWsMzaD5E=,tag:vac4we+Nyl0TRt/8yBykYA==,type:comment]
SUBSONIC_TOKEN: ENC[AES256_GCM,data:3bKCd5ul9M1WdxEIgBo/OczzZWZQFh0m6fCZDFJm1mw=,iv:COWfkdREsEpf+xnOfenOlS14gZe2LkTJnkdnTvREEyY=,tag:xBcxuHjaxph2rjdhAp0PVg==,type:str]
SUBSONIC_SALT: ENC[AES256_GCM,data:LaWtraS0,iv:8+xima+9M5487Yb2iQY0vGyF/WMEd0kk8W8VR8X/T2s=,tag:I3Du6AK/D6S8p7GdJRXlHQ==,type:str]
SUBSONIC_API_ENDPOINT: ENC[AES256_GCM,data:750ZYYbPvky+wFBMZACPasC/jHCU4u7Ocg==,iv:CMYShtvbJuE26zO1Mu+fJ2RbI0t3D6JjwD9vUf9nwnM=,tag:Rd3s56xTXZR3ZtaL/L6lww==,type:str]
JELLYFIN_API_KEY: ENC[AES256_GCM,data:bpGo8IW4w5KdYnyLU3kgne8Tgq+RRbGcCh0D6WtfWCo=,iv:MBNVQLwpbXDKRRGtlrcpZTH3DtRjDtTZ9P2ajzT7DlM=,tag:BbgumYFR+tSXgvZtxe3BqQ==,type:str]
JELLYFIN_API_ENDPOINT: ENC[AES256_GCM,data:yfuM86tCFHB5lc1M8oRwqi6emwmMiNIUdzHb7A==,iv:+LTgU7WXedG84jzAPomD3aH5AZOlb6LXAWIcPFb0gT8=,tag:NXfzFOrjco3EDQ/rr9Q/xA==,type:str]
sops:
    age:
        - recipient: age1m954z8ajdedsmvr9u89ud5v2zednmxgvvzuahpfy5fcdp97yn99ssy2wmm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreUpkQjB1blprdlVSZmJz
            SFhnVUlyMEhIa1JJemlTOGhlTGQxZ2hETTJ3CmI5WkxDTCszVHEyYnk5cjgzTUpQ
            RThVMDhvcWx1cytuUm9nbWVUTm4xaWsKLS0tIDVyWUJwajVIZGk2MzQ5amhzTzI3
            ak5MaDdjbkViSG8xeEF6dlllZkY1QWMKvQkZYSuqOELqMfd2TsGS7oEqUPDadMzS
            uKgmieYARxbE93rbk3VROZmHHXaD+ayDYlEiRQoqbb2F6FcykiUhpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T13:57:35Z"
    mac: ENC[AES256_GCM,data:hkFjruRcJQTggxGXh/zMI9NRRabF5OUTjqlxdIChBE8HCZxjqyZSpz/o7se8hrWAKG0kRBeN0vbwQnpk65lOUQBRd2qlEXiCwvQ1pLPvp855lcFyRvq5oUl5Lr+eOV7sE9DmOrPyUk6BtFre/AnuOpYFE7vxtX4gPT5OKRjgfo4=,iv:FehItYjJ4mOJjjN3Mnn4ZnQNZo7U7rIDLRitk7zOXpg=,tag:Ad0efTi4Gc5gpFsy4hl83g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
