DISCORD_APP_ID_SUBSONIC: ENC[AES256_GCM,data:YouxYC5TsCGwlPS10379RuJWTw==,iv:1eiuLpAbbSH+0Hdifi7V+l1Hod/PrxccwhhRSKb4irI=,tag:eyTxZZRZkXamufKHLa39Iw==,type:int]
DISCORD_APP_ID_JELLYFIN: ENC[AES256_GCM,data:ymfg1eYzoJzLeKB4sB85ovwppQ==,iv:oYfVexnfrYxSKPxOI8XWo1t4j3eO/9gFuc8pE0fcKNE=,tag:dDLuClOoFSjYElMiFR8izA==,type:int]
DISCORD_APP_ID_INTELLIJ: ENC[AES256_GCM,data:LHVesn3l/AN6zCGaVW0ldtZgkA==,iv:ExkikmPL2F3DZMZ4apVJPKlRjMuq+OXw7Eg4gXSDTms=,tag:81zWJZJQSL8wa0tT9urtig==,type:int]
SUBSONIC_USERNAME: ENC[AES256_GCM,data:1e38BvrchH0=,iv:4t3clksFO2ewLENR1H768b8B2oyeOfYAD5xh97+ehss=,tag:w+WzYwoEYyvD+NwA786XyA==,type:str]
#ENC[AES256_GCM,data:jj5Va7W5CHyMXNZZpefU+T6o3h0/sy1U,iv:O+RAA1wJu0BsJIAqXOnwdWHmdxnrOwNwM4qWsMzaD5E=,tag:vac4we+Nyl0TRt/8yBykYA==,type:comment]
SUBSONIC_TOKEN: ENC[AES256_GCM,data:3bKCd5ul9M1WdxEIgBo/OczzZWZQFh0m6fCZDFJm1mw=,iv:COWfkdREsEpf+xnOfenOlS14gZe2LkTJnkdnTvREEyY=,tag:xBcxuHjaxph2rjdhAp0PVg==,type:str]
SUBSONIC_SALT: ENC[AES256_GCM,data:LaWtraS0,iv:8+xima+9M5487Yb2iQY0vGyF/WMEd0kk8W8VR8X/T2s=,tag:I3Du6AK/D6S8p7GdJRXlHQ==,type:str]
SUBSONIC_API_ENDPOINT: ENC[AES256_GCM,data:750ZYYbPvky+wFBMZACPasC/jHCU4u7Ocg==,iv:CMYShtvbJuE26zO1Mu+fJ2RbI0t3D6JjwD9vUf9nwnM=,tag:Rd3s56xTXZR3ZtaL/L6lww==,type:str]
JELLYFIN_API_KEY: ENC[AES256_GCM,data:bpGo8IW4w5KdYnyLU3kgne8Tgq+RRbGcCh0D6WtfWCo=,iv:MBNVQLwpbXDKRRGtlrcpZTH3DtRjDtTZ9P2ajzT7DlM=,tag:BbgumYFR+tSXgvZtxe3BqQ==,type:str]
JELLYFIN_API_ENDPOINT: ENC[AES256_GCM,data:yfuM86tCFHB5lc1M8oRwqi6emwmMiNIUdzHb7A==,iv:+LTgU7WXedG84jzAPomD3aH5AZOlb6LXAWIcPFb0gT8=,tag:NXfzFOrjco3EDQ/rr9Q/xA==,type:str]
sops:
    age:
        - recipient: age1m954z8ajdedsmvr9u89ud5v2zednmxgvvzuahpfy5fcdp97yn99ssy2wmm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreUpkQjB1blprdlVSZmJz
            SFhnVUlyMEhIa1JJemlTOGhlTGQxZ2hETTJ3CmI5WkxDTCszVHEyYnk5cjgzTUpQ
            RThVMDhvcWx1cytuUm9nbWVUTm4xaWsKLS0tIDVyWUJwajVIZGk2MzQ5amhzTzI3
            ak5MaDdjbkViSG8xeEF6dlllZkY1QWMKvQkZYSuqOELqMfd2TsGS7oEqUPDadMzS
            uKgmieYARxbE93rbk3VROZmHHXaD+ayDYlEiRQoqbb2F6FcykiUhpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T06:45:06Z"
    mac: ENC[AES256_GCM,data:e/v8wJklf9I2H2KUx+6A1Vy+LqHHcoF0XToAEjvmoSCmQsOgCaPUaTqC3n4Dl4cBP/S4S5LgE9sMC7QB2z/F9bVkd1Mxn7/s+59O2PHNqR2YX+JNhTPeqyvJ3QCn7otr4wIcgltP9OWlvjeb5D+sIz7N0LyQ6eKhvfWaoz+NugQ=,iv:b6rH/pFzak0c90wTkdAsjNEsq36X6Ebt1rYUsD7Fa4A=,tag:okBAdlXusxjhhQ6Dmo4/UA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
