accounts:
    - ENC[AES256_GCM,data:Ow0B1KJNq/pFoO9XKQl201c=,iv:Hv4H2aslW0tjdjejaM1bc6HrRx65/v4NRr43I8wq0ks=,tag:at7UNz/TAmyuQVWkwfGuBw==,type:comment]
    - ENC[AES256_GCM,data:z51aWyVtaXXHvfaigYYcAUZFjZov3w0CeEBGQNSJwsWx+jc+H52defuyczavK7gHCVo=,iv:hIly2iCjAe9nPLRotbBmmh8xBilC+7YfuA7CwCNAw9I=,tag:opVfdkTkbPKQnOhWbNDdTA==,type:comment]
    - ENC[AES256_GCM,data:nZMAiVB3Ig58VDWDtA==,iv:fiIwspXOUYzofpwqSl1MBLj4/2FJwpT6PuCLOrzLCTk=,tag:4ad7UzWO9uqtYpLJ7SpYag==,type:comment]
    - ENC[AES256_GCM,data:D9Ze2C6oqx2jIDPiQ91Al6aW,iv:hB7LLhBn1OiST0GPWVCs6ReBwfmz0gFenBzp2p9cruA=,tag:0rMbSbFkIKvhA/IiO6kSDA==,type:comment]
    - ENC[AES256_GCM,data:4TFKgMAlSkGJF23vv6G2ATv0,iv:IMxM7zjPTGHtOMPz9G23DxxiqBi/5+0ngwbyy8UsKDA=,tag:p5wHewr5gCX0d8ltqS3b1Q==,type:comment]
    - ENC[AES256_GCM,data:h91tW6KPwrxHvpcU2IkcnwRbftQ2uDRKPXowNbiPx1kHpK7O4lei/sXfEzGJPTGIJ7Lk7qwlQVzTaueNH8Wa9e9Kc97d60Da8lxJ6mf/Wmw/5lUNzxDAvZtSS+W6YOwnCdF5qsQ=,iv:iG8Pe1YdA/9nt46p8P7xSbaT1frssP33tS3XmPpdXGU=,tag:LRtap4AAoo6ab2wXD4FklA==,type:comment]
    - ENC[AES256_GCM,data:NkYmcNXg9KisQXdfj05p5YabFA==,iv:wWTLrWKOUFp8gZvW5VBCue9jPD5tm0jM4yx4zAbZ6Ew=,tag:X8D1pXLRlsAD3EXRv/wjSg==,type:comment]
    - name: ENC[AES256_GCM,data:LxU3JO8pmN0=,iv:OQTSt1LsTVEZ94jv+sxOAWTurf+R4xqGYbW+REId9SY=,tag:1d7622WJJCF5igNaCquluQ==,type:str]
      credentials: ENC[AES256_GCM,data:SL7x3twDwoh4YjBug+6OsCgWa8f2ZMpxNAcvvNgnrgo=,iv:aXadtSaiTOeC7yDHblVEcso1ukcc1URie1y8n8ifr8c=,tag:m0tkFZkWq37qqOD9XB+2KQ==,type:str]
      calendars:
        - id: ENC[AES256_GCM,data:RKD2a41yYw==,iv:Zkwx3NrDPPSHjukeTOBXedzoXdIPypQ0nERPRAioD4I=,tag:Mh75xu1c/fFpznzeaDBTzA==,type:str]
          color: ENC[AES256_GCM,data:PWXrXA==,iv:0sj+dJy1AYphR0BExFmp/6TcJOMfQj0Ww0Vs7UWFQgk=,tag:2OayI/rHpFIWbGHhOHHXHg==,type:str]
        - id: ENC[AES256_GCM,data:jWdmCaXonclbPXfHu6WsguCOplnq9cz/kfHQmZMGS9L26839YP8gRDNlfwEjMJ3Ig3Ay0V18N05XAWwXrki+aHS2N62vPn7AeC9xFG3+DiAZeRjs+06ebO7GTjM=,iv:8EW0UN/s1j/fZYOPVt+o7r+E7YS7lIGAQtzJWrNWKxY=,tag:sgco7K90N8v1nthLGaGWsA==,type:str]
          color: ENC[AES256_GCM,data:RP4gGQ==,iv:kqLBCDP3yF5MzcdhTyQF5UkAFBRb/xcZLwYzYwjEHjg=,tag:NO7DFL3nR8g4I8fMMF34mQ==,type:str]
        - id: ENC[AES256_GCM,data:yeqv/1RmxhFPpQS+/dXhK/CynVMX7JYo/fpRm8Fpl6od1ELggNAHDAPeT17aYYgIJPmOy7nmKB+8uoUiLLOKnHpcxwW4jgoMf1T4DvSj3rndt3Q/g2kFKb+a9OE=,iv:H2AxzaboHKcAJ0ub+hPp3R25zdMRcWl9W90ayQLVs0Q=,tag:dcHwvpnCmv0B/wGrpS3GPQ==,type:str]
          color: ENC[AES256_GCM,data:g7LSoZA=,iv:gkk9tLjgjJwnnTd6N3hCznr6JiVr2fujpyL0DVPghtY=,tag:KiXoTyAW5YfDeOl5+KZa7A==,type:str]
sops:
    age:
        - recipient: age1m954z8ajdedsmvr9u89ud5v2zednmxgvvzuahpfy5fcdp97yn99ssy2wmm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb3pIZCtVaHJxc2crZW5z
            U1UvZEZiRkFzMUFSM0RrdnJPVHErSTlMZUJZCkY2NHc3VXdSWnA2VyttM1lPckVl
            ZmNhd1gvckgveDRsWGJkbmpmOXpYTVUKLS0tIDVzcEZxcDlwQ210eXo4Y013WXhJ
            ZnZ0RmtRYnU3SmRweFgwSnp5QVZUenMKvpN7g8q6K07Zm5w7jEPgiREqatVfAB3h
            tTvSYi8G2N6dEqIV4RS5JjwwoRyGt5isMfDmFEuyu7m08CJ9QkrU9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T05:11:17Z"
    mac: ENC[AES256_GCM,data:tQ4xy4M9FIzUBYEFauM0IE3hKhXCGcOTF+2BTPAAkTqSWgzRfxHO4x9Mb4TELQ5DY/r9Qe2uDgvhvozIPs0OYNye/X7wbBXdkimEpPIPI1BQ3mjjDgxX0Deq/gYib4ICpvERxk4k8zCjZXfDk/F7PCLlGpjnoYx1xsuIRrujlMM=,iv:BQDXNIaljnDnz2bbDf6t0yVbPnMc3Z6ZBrCzzhOHum8=,tag:kh5mW58Chq61Oc7C2dFzbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
