[org/gnome/shell/extensions/auto-move-windows]
application-list=['jetbrains-idea-7c12a7ea-5d92-4bd3-a9dc-ce0e627c7478.desktop:2', 'com.valvesoftware.Steam.desktop:3', 'com.rustdesk.RustDesk.desktop:3']
