[org/gnome/shell/extensions/auto-move-windows]
application-list=['com.rustdesk.RustDesk.desktop:3', 'io.github.tobagin.Ntfyr.desktop:3', 'mullvad-vpn.desktop:3', 'jetbrains-idea-cd267b56-78c9-46b9-ba84-7caf4758efa8.desktop:2']
