[org/gnome/shell/extensions/touchpad-gesture-customization]
enable-forward-back-gesture=false
horizontal-swipe-3-fingers-gesture='NONE'
pinch-3-finger-gesture='NONE'
pinch-4-finger-gesture='NONE'
vertical-swipe-3-fingers-gesture='NONE'
vertical-swipe-4-fingers-gesture='OVERVIEW_NAVIGATION'
