---
privateKeyFile: ENC[AES256_GCM,data:C3xMKH/YC2yCk5EoyRWqplY=,iv:wRAv9sg8NOBQ2NctOvl5TRYg6tsEDt4CgBxBN5wRd+w=,tag:ZwgjDfYX3gchVH3YTWtKqQ==,type:str]
workspacePath: ENC[AES256_GCM,data:x1LeRD4=,iv:cDDuWvu2wF6eWWgWVYKMGrntRQmvdgRHX91hH3NOFdU=,tag:jmsFWqnNiAIMLgXepdW49A==,type:str]
gitUsername: ENC[AES256_GCM,data:y03l5VqdwUE=,iv:O0I2RRPbk70duPsweqRRJ/hT5nw69NSks3D26LU+ZOE=,tag:Iam6+C2CjQdnG7ljof7zqg==,type:str]
noCategory:
  - ENC[AES256_GCM,data:G/lrzcoQVCkFAQ==,iv:0T7FTtYWnFcbpoxqGc+lKtuz5NMO0EY+Pqs/EIKBBQ4=,tag:HgKKMHAa/yrcHN/GGf4qCA==,type:str]
  - ENC[AES256_GCM,data:tfq3xyx7,iv:SWWoAA7E5i+5q8eWNSTHxxDIb+D+N9SwRrjbJkpH5vA=,tag:qjD6KOlNwt4rjiBw+Vt8Ww==,type:str]
category:
  - group: ENC[AES256_GCM,data:6wcFX2sbUw==,iv:PK6LL2ON+w/oxJA0Zd5IBEmNMxn8F+6j2SOoCpOJ6bQ=,tag:ZDeDh3R7N8pglSwdnlB/UQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:ffLgO6+9kla9vOnq1cKA46Yt+7Q=,iv:sUEUT5VWjGGAfJMRNckjJWpqhmniaSqE6huazWK4RMM=,tag:4LR8zszKSw8ftEGD8otD9w==,type:str]
  - group: ENC[AES256_GCM,data:X0ajg0o=,iv:OnLJaenjmJMKDBzV77by285Mx8kZJOrJamw1ae+T3Nc=,tag:gHC0jhJ+29PleITePkq5mw==,type:str]
    repos:
      - ENC[AES256_GCM,data:XluYLB5JxIHXoVI=,iv:HEuH8jonb3DMHcpdlacMN0YShNCMDWKbaxqaUPP7Njw=,tag:ioYP8emyAKNwg4tjgNMepA==,type:str]
      - ENC[AES256_GCM,data:AkiZ/4gzQ+8=,iv:fcMNA3jq7/SVgNiGsbwErz1WYMfV0qNrJjIS+d7cNQg=,tag:Z7TUbrDSemBk0dGGXsEeew==,type:str]
      - ENC[AES256_GCM,data:NGos2BUF0K80yg==,iv:4/dTdYaxxkCYJVpJr4sBgYD7Ldg9MkkCmPiz1SodTAE=,tag:Iy2VzfUJKWBhAzYjyRoGNQ==,type:str]
      - ENC[AES256_GCM,data:FFxGaiuV1IwW1/xn11Q9TA==,iv:kz1t+OnOBEfSwZm8Bw5x0wjj/UOhjwuuiH6/BaiWG8w=,tag:g2ymizBkMRASPn+zSm6Tug==,type:str]
      - ENC[AES256_GCM,data:PvZX51U2GKqHQ41ibsqnH7w=,iv:DFy/AZElHFS/bz26HaP0myGanvcQuf2e/8wjqJSTUiQ=,tag:Wh2ErK48LIc9rdQYKeraLQ==,type:str]
      - ENC[AES256_GCM,data:wk6Ga6arMfI5Uotn01g0S2s=,iv:p/4yNdAN3dwmRcgowUJdw+tqjLpUw1rfk9rpslWOjMY=,tag:sHw5o2OR2TXBG2lH3x452w==,type:str]
      - ENC[AES256_GCM,data:6qKICaU2EqTfCzI=,iv:aZUE/RBpAMbn+lG4qN18z2oy0WzdhyY7oGVpmA4Mjgk=,tag:qFNcUA+p6BvduadBuuCxUg==,type:str]
      - ENC[AES256_GCM,data:lOyaZe9igEPXGRd3/Q==,iv:dr5PSZ0BBYAJcdQn/WjWwqkEG+k1tNNpS6VyqrpkoLU=,tag:Pse0mch/n4JAO767lZnrbQ==,type:str]
      - ENC[AES256_GCM,data:lcQmeg==,iv:QYXMf+pBeAlvSOEk+ZgWXswKGSQlVOhLsuKGwUAYiLM=,tag:ez4td/VNgholmXOE/8CvpQ==,type:str]
      - ENC[AES256_GCM,data:JcFdRinFTHVO5+0=,iv:iidnDG30Z8p4VbSuNrGyRiwVBxPmp4PxTg2dMhQynfU=,tag:J+Wt3bA0mzCew3JZo2q43g==,type:str]
      - ENC[AES256_GCM,data:uNErI71ByUGQwrkyM/2c,iv:CeMsXavChSjxrgW+erDPhLya3GCjXr12DRtbDWwmI+8=,tag:jP9w32rWwXhESwT5tgFtCQ==,type:str]
      - ENC[AES256_GCM,data:ZSVBCGi61LxE8oMe2U48,iv:ZdYAowbXidg/pdhGc9GA4oCanLwcSEIlqMhcTJbx6Ck=,tag:OE2tbp3xi5Y6pmiI8ZlgJQ==,type:str]
      - ENC[AES256_GCM,data:aay9IqoGhd4QaI2DOw==,iv:aEJjHJSgUaO8mOJade/Y1RbKRI8WZXglmAVFErOsyaU=,tag:Ru+s94KPAwYlQAmoV2kGVg==,type:str]
      - ENC[AES256_GCM,data:rip+i0Ma96hu,iv:f0ZYd/t9uI7xGkC/dW43qFnnv4iK6qm2Xh0O+hfbZ6U=,tag:CXwoANZPIvcNNGfnNsJWYg==,type:str]
      - ENC[AES256_GCM,data:8K6t+TLg9nuVv5g8xQ==,iv:34dWXwoXKVOGCyQVSxNxcWh5fthGaVOBQCPqWiFLCpw=,tag:pXBEbnrGEqyybvhJwjH6cw==,type:str]
      - ENC[AES256_GCM,data:TkzHiOZuiKlhsRg=,iv:mFZoMl91gpAlGMLXZ2i5zQoGPbE6z1KcPh61DyH95K8=,tag:I84BauZvcdP4Tf3TGFizfQ==,type:str]
      - ENC[AES256_GCM,data:9dtFZj4YEVxANuo=,iv:4bOdpbmaV7R8YINczh2dGjzvTuVTf7nTBs+fkZgrBlo=,tag:oRj0NV8oN9qaXGUKgUHqBw==,type:str]
      - ENC[AES256_GCM,data:xnfhRPccWAQ=,iv:IJk1ktURMUKvz1RJ+8Xtmyx05f72e/QMEULTeiFGPf0=,tag:wvjLynR9PNJuazT31MteuQ==,type:str]
      - ENC[AES256_GCM,data:81AZlW+4+Rvs460Sur+1m0oXVX81ORxuS4kD,iv:wLk/7lDxUPRgVKyJjnFiQgjLA9+EVF++1Dy4m8HEgxs=,tag:cP/Nu7F/LxG+mrCJ5BryTA==,type:str]
      - ENC[AES256_GCM,data:Osx0NxYtkh7VXlA=,iv:czdkM1QAsn5ygAUgAPIlTyML0y9apwiaZk9I5TnbFMs=,tag:Ig7pwFZ6uLJhIvOqMGdFjA==,type:str]
      - ENC[AES256_GCM,data:wMzzl+yrb7tb8qQ=,iv:cMgjCvjk0Evin7Wu2v68LuTjUt2isy9G7G/hAjAe6fQ=,tag:jXfVKL+Zmvizz983Pp/8AQ==,type:str]
      - ENC[AES256_GCM,data:oXO2e3VXXvsFrA==,iv:A2HmNMH4omQbIJSomSL0onFMRFHAi5nlxx3ldJXNOZ4=,tag:gcqkkcjcVMIZErBXR/T1Xw==,type:str]
      - ENC[AES256_GCM,data:xdaHq2Cxp00rwXeAV3YUT/ctBBq+RgHc/xgF,iv:Kobts5VC5tKd6lyUNhnCDmRLEW/zbxNpMh9GHsupUJE=,tag:r+6KvyMYZ0ccH2bndjJ12Q==,type:str]
      - ENC[AES256_GCM,data:t14LKr/6d3N9EalrFQ==,iv:JpaNX9epa4KLVA9K+ABa7jBQmvhq2VgMSUm/2sZru5k=,tag:VxVpeBp4BUI6TveXCdCFaw==,type:str]
      - ENC[AES256_GCM,data:LK4ppgn0Dn58BiWtrOGvWew=,iv:kHwCikKaKGMVpzmK6F+Er5DdYqvgEvWXFSUacedPLBE=,tag:iolYZ964sy1AEUlyhfztMQ==,type:str]
      - ENC[AES256_GCM,data:Fnx/sHJP,iv:ymr2YXa8ZIiM6MjFA8JMCBGlmTegvDEKq1BzwxqfMqU=,tag:qy7jF7aYiMNFtwDHuO8Gzw==,type:str]
      - ENC[AES256_GCM,data:3th12XrtPGcb,iv:PHgecmxNrnZfn2GBJbsX5LC0Kd2UkSBUsJQMiwAKfxY=,tag:jFR+7wHKxR+TaUXR1bMfKQ==,type:str]
      - ENC[AES256_GCM,data:ToZDvu9HemJ+ug0Exw4=,iv:5aCJN9fBTbwrGYIZQQ82+1fEnoN6SkD7DpxZnEgRLz0=,tag:wOuOImqcY7kPC5TIrydfZA==,type:str]
      - ENC[AES256_GCM,data:dSuNdSjanEz6,iv:01T8D1+w2XgyeBD5COzgX2C6z+kAADcaNO/WMLAHnSQ=,tag:qhYePw5K7jJMaMAgbVslvQ==,type:str]
      - ENC[AES256_GCM,data:6olWVN5Kbg==,iv:VyKpQp73G2iQLI2umlZ5ffJPWBmD9gdFrCVzVuXdxvk=,tag:imDeUTo7th+PGG2Gibx7pA==,type:str]
      - ENC[AES256_GCM,data:D+Z8y3LoS2BnZ9g=,iv:8nfu7VtdNA7AEsdb39xf376E7+2LzlppFFP6CHaMARg=,tag:1FyrmcV+kbtoeiqQ0XbrmQ==,type:str]
      - ENC[AES256_GCM,data:32qoTUTorXSI6akYi4ek6H1xfg==,iv:9/zU9DSjsFL79dEIBnWmHyPYJWqbiDUaDFdi3XUE5Y8=,tag:IXr0jOdJoL6TEUEvWLOw9A==,type:str]
      - ENC[AES256_GCM,data:VtbcLkAbDmmt4RkBtw==,iv:ZzpXRYLbx0uald2dfzzWHXMT3inNH0LC3QJKfahuIxU=,tag:y6goBnFeh4fQmuImIrCrEQ==,type:str]
      - ENC[AES256_GCM,data:B/0G,iv:G0kYbb5xdQvKGI26k8NRqexvEvqGRke8xjAF1TwlHzw=,tag:P2VW8eSH5gx/Bo9yCEYO0A==,type:str]
      - ENC[AES256_GCM,data:ThSnCg==,iv:UQsUt0RdvV+PE/9Lj6CdxkAWcFwGg5BOQwIuWjxvWu8=,tag:uEm6Z/ntMhIcGr29v4DhIQ==,type:str]
      - ENC[AES256_GCM,data:cY7KALelEMXlnjju/CCUSw==,iv:42Ba9X8C03rGZUCncubtdIf+0FPXKfx7H29YFymgwec=,tag:m0xfddAPVHjpHy98NUAFjQ==,type:str]
      - ENC[AES256_GCM,data:fAhggpMsCB0QncSX5TZGwBTS,iv:ytPiwwWTNjhD+IPGGlFerPDHVJkAVhEkZpcDFL1F3Po=,tag:Xcqe5GDuY/hHP+lJSb0xuA==,type:str]
      - ENC[AES256_GCM,data:C46FaaPFnXKJ,iv:uMnPz3IXTFLoT+DlQNlKHtNH7z8wKebs7OxVsX9s42I=,tag:sabLTXUBahbj+7kVyqQekg==,type:str]
      - ENC[AES256_GCM,data:9H/gdK+z045U2ccmkg1t1g==,iv:nZikyZ2TzvHok0NOqvZKQOh+qU8iirnBTh54Q+LeTuk=,tag:veM+M5zHwocgdpuaBbFpew==,type:str]
  - group: ENC[AES256_GCM,data:jv5p,iv:4ey3lZgh5GPsexX7gKAEFnysJ2IwbJKInDEkVq8CmA4=,tag:g6rzAYGuuaR9kiE9nOiOLQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:rR1NLU27g1CwfVdI,iv:cbCiSWofKU7bGo+YhFRrlAXkXchPwY5QfNm9O/0NH8c=,tag:A4Pbo9j8G6oevHsMsFEBcw==,type:str]
      - ENC[AES256_GCM,data:z1Ce,iv:P1PAX98kmei0wxy6SjNzak/XHfjJw8AUvc+qT3S/dGI=,tag:eNHnMjDg6ZFlEckZn0MgUQ==,type:str]
      - ENC[AES256_GCM,data:nqpDxvW+lOx+e7cXFYtLcLuwsoxTq73uzXh5grYZrPs=,iv:5/Y0sFbmdaLvoZ/ZyhNokPiSjJgh/vGmkW/C3BldTQU=,tag:r7LwpxfHE/68pP5iaa6cGQ==,type:str]
  - group: ENC[AES256_GCM,data:1Vw=,iv:zXSf2G/XGN7vekbjQ6Xe55cTM/d2nD1J2gtaStt6La0=,tag:za6sEeqWTmYMyLqlIgCENw==,type:str]
    repos:
      - ENC[AES256_GCM,data:9A9NiCIJFjxfVpCROxVUoQ==,iv:lSiN1pkZBr02k1DOtlmP44LbKEUrkbJ9z1qckYJx0Zg=,tag:RsRCe3846Jl90ijBhpXW/Q==,type:str]
      - ENC[AES256_GCM,data:F7NcK4cqhFDiTRFhSnp6wU4ud9PgHQ==,iv:2fYk3hydpPpQd94jLzcppVq0WCbiUlVrkhSCPnaT1VE=,tag:nyKySHAws87UIIlIbwqD2w==,type:str]
      - ENC[AES256_GCM,data:qYh7Qfdo/TKZymZa2uocd7sWhRU=,iv:ibn1bBwmSKXTbb81RicEzNcpTdhnAQt9bDe6EgVDMYY=,tag:YDh89pmIYvH124KqhdbLDA==,type:str]
      - ENC[AES256_GCM,data:4AA5VdZe,iv:oCKAFEe3AT779BP8kS6Ci7dLvujLMrI8F3EfOBDEzyc=,tag:yv4/g129C01tarbXU4Q3pA==,type:str]
      - ENC[AES256_GCM,data:RKsv,iv:TULGbfU/QJLsJ2LaZbqnMtpgl1Q4JSVAxEeNgTdMIes=,tag:/9CLZsVH8rsuLu8Ni/h8cQ==,type:str]
      - ENC[AES256_GCM,data:LOpKY6ej,iv:97CdBRAuLKbaZ20eo4fmd2JFILSrMNl4WFmp29AXcQE=,tag:2nN3LXqipDTUC67rgqu21A==,type:str]
      - ENC[AES256_GCM,data:P0ffRtA7Lrgwfa8drTE=,iv:VpBRgRboGhR/dkwYCRSWVKGfrhfWKXe2uyTngP/dh1E=,tag:J25rjCOaydzcUTWy5YGJ5w==,type:str]
  - group: ENC[AES256_GCM,data:LPINv5E=,iv:dbpsQCoA7HwuD1obJloGv1ieX5ymqimSt9akEefOMCU=,tag:dwy7xrB/oerOCC+YqYgc6A==,type:str]
    repos:
      - ENC[AES256_GCM,data:n4rBWtr2ypPf,iv:R/KdPiGevzISrU1SXFC9kws/jml7s8E8H8KipXFrC8c=,tag:od7YtM8upG1sAQ2Z/w9v4Q==,type:str]
      - ENC[AES256_GCM,data:wcmf/H0=,iv:RkceP10siJ14zLMS00TqH4bRJZFssxDJp0OTX+7xOXA=,tag:y3821trqLWXyThg73JksWg==,type:str]
      - ENC[AES256_GCM,data:Sb6ktGoTEdekZNi2Uk0=,iv:nfb0ziEzdpYP/kcf4aWgUkT9QCuSGr9SyRZk9+eED6E=,tag:8KHAutOVBD+/HmdHmWv5Mg==,type:str]
      - ENC[AES256_GCM,data:JMYMQV3DbhrX+Q==,iv:fNFu82eFnnmiJ/cXkKCa5IbEZkclARFcau4/sZVpnCw=,tag:q1cCfqT9k+P26fdzi59bzQ==,type:str]
      - ENC[AES256_GCM,data:yjvrYhEwuMr3r9SBOA==,iv:El4bprRNnbpc8Xbatt5BLPdujC8f2lkeIlB8Y1Cqfms=,tag:leIkuSGPICBeWDWcAG1BGw==,type:str]
  - group: ENC[AES256_GCM,data:6cimiGPTc0Y=,iv:I41nf2fRKJttGJKQfSKEFOBXKc7YLQfZmVu+HpQWCY8=,tag:sW0DcCSlFz+egiar/g3cIA==,type:str]
    repos:
      - ENC[AES256_GCM,data:Lct9,iv:E297y6C3LUQ+EPjueH61Xh+X3OcbvqEh/2y+g8p26qo=,tag:pcxSfmdV7cmgCmj4sClVJQ==,type:str]
      - ENC[AES256_GCM,data:khAoUp5jZKHxAQODdZU=,iv:HIZ/RpGmQlOkLkZviW3GiYWXsgc9exL5oo6g3sbE74s=,tag:5cwU9EbR/Cbm3TlYkRqs0A==,type:str]
      - ENC[AES256_GCM,data:yiRLsqDV,iv:MgvMuENEaBhjL0I29KhcAmHCFsRmcirnzvMg+5ZYk6k=,tag:VSl0B2EIckgiD6ReIX/n/g==,type:str]
  - group: ENC[AES256_GCM,data:lx1B/641eXidLg==,iv:Xou3ZxbjKC5NKdWi76Ppv/s6d2+rgOWCQ1hniQs2AJo=,tag:ei2KGdc+lgc/zwYjsaizew==,type:str]
    repos:
      - ENC[AES256_GCM,data:siuN83uWyWn7xkMD0XvM,iv:PPrQnJuSYljpSDShWd2o6tedc6L6pfnWuM6SfCjLzZg=,tag:x8IkogAgyd8HwllFSPH+ww==,type:str]
      - ENC[AES256_GCM,data:407A344y7WYf/s2sZA==,iv:BTEUOB+DHuFWPiK5ZFxulvy9gE7/wzbLWRQqPMyjxYA=,tag:HXfiE5PuepcSWAuAou6W9w==,type:str]
      - ENC[AES256_GCM,data:KZSIUtlWDF2V,iv:o2HrSjpNus0eLsxG6/muIOC2ksqPsSeudSKyff4ygBs=,tag:Not3WjSWuq4az2LJKqvLsw==,type:str]
  - group: ENC[AES256_GCM,data:LiIzi7aV3Zg=,iv:ZOlAL3RlPAaaRyio3XJAC1y3KlkB8aYJibN+CMowYsg=,tag:9IT2BOeTDpVC/ZxzBES4CQ==,type:str]
    repos:
      - ENC[AES256_GCM,data:lwMo0iwrJRY+Z7k3xA==,iv:85eVwbxBS9EQFqHiu+NUPKL8PmGJ19adY0ITwGQUUgE=,tag:Ky8/lQlfIuO78HSX+7stXQ==,type:str]
      - ENC[AES256_GCM,data:c4cD7QoK+8ouSIN7,iv:Xq5uNTU/0u/a70DYDVrh+pBBVeq3oxu3Ho55QALqTnc=,tag:hscozGgluO1MtpiwSHSbGg==,type:str]
  - group: ENC[AES256_GCM,data:P9owlWA=,iv:8eW2qTDb3hYbPNov9n8rJKQw9d0N1wtNrB+lnM515Cc=,tag:3jpoaHhLUp0ZpZLIlBP6gw==,type:str]
    repos:
      - ENC[AES256_GCM,data:6ctHpIS3C+gBolOg0N7VzFxY,iv:aA32lu6GsApbnSmZ9v69pJfpGA7w8NLBVG+O6QGOVSE=,tag:p8A+oZQxYsQTzzsS5ohGHg==,type:str]
      - ENC[AES256_GCM,data:RtnoYF954ANyTD/LIi7J9Q==,iv:19NkCjTnt9q+nXFTLBk0v8+S1j+U9GUmr9mn5ziODOI=,tag:rK0Vvv+xU8FYGu7oULrhtQ==,type:str]
      - ENC[AES256_GCM,data:nlmGDKxtuAr8ASQ=,iv:fJ3EcM3lI42KViU2egaVHnJJ2ayV1p+3wA9R6iXu960=,tag:jKafu58hlzQhVjkS2qcHiA==,type:str]
      - ENC[AES256_GCM,data:bsiOU1U+lZUzHwY=,iv:RMklmlk2K6xOT8nYI3E1x0w1ssS2IaxuiceKHnfyvqw=,tag:IcnG/KN4gpvgn43plL8JxQ==,type:str]
      - ENC[AES256_GCM,data:OoNsicLHEilsknCXQg==,iv:vYaJWxQLwc934Y5iTGuHPuFM/m7nCbI6nPB47rwKbSk=,tag:EhKBnDfBNmDUcuS466vIjA==,type:str]
      - ENC[AES256_GCM,data:UgEKylEd4KkKMMKvw24zgf1gxA==,iv:i8HkTbuJbPTCvtB9BjAH4FKA/IXNgZja++GvEvvPxYg=,tag:wuTwIP5AemlLQU6+io811g==,type:str]
      - ENC[AES256_GCM,data:ip5RzsN/wzCsD+kCSPwIDZog8A==,iv:8FYzqFIvgo1v/6xN4ydOspvEs1m2NDAQwoWuuCcZXro=,tag:9FQhbBo0kjH3ylY7eQcI+g==,type:str]
      - ENC[AES256_GCM,data:L18J+P5O,iv:VxrCaobeHC3JBb4MwPOqiXhoA1mzYmLgbYxpWFAsytQ=,tag:UWpO/J7khv+Nw9ImYiO90g==,type:str]
      - ENC[AES256_GCM,data:U9HxjlH6H9WgHfmHRaQB3IGX5g==,iv:bzuhUpP2K+a/9njSxSt8BkC7vztCEH1eJNK4C/RTo3g=,tag:59t4AuJib88KGS7CE1LHlQ==,type:str]
      - ENC[AES256_GCM,data:ZmsvtliihXuP9Q==,iv:IvnDLw7x9TWA6z4dKfyXIwPnfvomnsb1Gck64KNo2wE=,tag:ONLxqht+9q+xSrVaRqqY0A==,type:str]
      - ENC[AES256_GCM,data:bMpaKDrBH5YQ,iv:JK0qlbrSFWiXoV6hGL5V4GExqDlbGjPFpX1iqbOvCwk=,tag:UeTCXNr2br7CqVPifA+dZQ==,type:str]
      - ENC[AES256_GCM,data:iLILkQ==,iv:weP0f0wJNHiPVHsHYruGpZPds5/5pMvo+Bc5PZQd3DY=,tag:3I026Z7POU++BVIDnJ1uJQ==,type:str]
      - ENC[AES256_GCM,data:YwJzvg==,iv:FljWUR+YYnbljfCG9+Pq1slgmhr5COOPuhuH+tOTyIg=,tag:vplwrXG5ZXQ1QMiAu6c76A==,type:str]
      - ENC[AES256_GCM,data:2TuGVHtEyRv8eViG2ijTEg==,iv:y/K1zUoZc5jQ5oHeWsuiPDhO3K0cdNvXfAFOgDtYAdk=,tag:1i6q0dVyqwFEOrAMzubfZQ==,type:str]
      - ENC[AES256_GCM,data:yQdBQuhLKwTjD0bwnHs=,iv:jH0dfJCp0bLZ9CgvPd0vzSeMjdFBOcp2kgQORI7oHEQ=,tag:bUH6+2YCd63ABbKzwjPOxQ==,type:str]
excludeRepos:
  - ENC[AES256_GCM,data:ylhaKyjNWbnFz13oFoC9,iv:QiHT1y5kNkKp3D6wkBKTRj1ajiJFBIaetrh6PpY6sRo=,tag:Mskjencyij3J+QZZ3AsLQw==,type:str]
  - ENC[AES256_GCM,data:YHMRHAxjTjY=,iv:21zh7LD4go2BNxOZvsAgjPtrF0mURQzQ2/D1ONFXSEs=,tag:qHGu2jQnM/aXDjVluWTCrA==,type:comment]
  - ENC[AES256_GCM,data:rlCshi0E,iv:5ia8tB00b0gY84DxFs3kBS7O6kKUfNIO2nY3B7umqIA=,tag:BK3a8zdcKZJFVOzJa4MYow==,type:str]
  - ENC[AES256_GCM,data:a/wgEJf/lpInXJehk19Oyns=,iv:UgJlppbqm/GeWTTSZJ0KhAhXjeZNChGRVeWshPM3Njw=,tag:0rsHufIANgDMvXKrLOp0fg==,type:str]
  - ENC[AES256_GCM,data:jU4925jHHKW/AcSqhALlIYP0IF9d,iv:hARYaMeh7TcTKb83YIOsfobF6kNBOtcw3hfKQ9EJoZk=,tag:0knwAFd+vCbDcKVVsO09rA==,type:str]
  - ENC[AES256_GCM,data:0fsZWFGf+d9INvnNPEW2,iv:BoSd2KWhCqxD4apXqBMyigPwvxJX3f3xp4gkFQMErAQ=,tag:iRgNDujWOFsok4ZpUMI/pA==,type:str]
  - ENC[AES256_GCM,data:ox8B7T4XXA==,iv:zEKN70Iw9oSPbGnnfvYrvjTYIRrVywFR0nf2dvffZRY=,tag:nfuKpynuf+w8fP61Lw2Apg==,type:str]
  - ENC[AES256_GCM,data:kqo8EWUc,iv:bmP156EjOMiG2gNCm+6cpvmKcQiM0lqQRr18HvhV9C4=,tag:/xYuOPY9NSWPEn6tzuMsIQ==,type:comment]
  - ENC[AES256_GCM,data:2pDYKScrFwp15SxhpVAMOMsa2n6cuCaO,iv:VPSOkgvVFI7JNds+l/auyvKe95anRsxKd5OolWhsSSA=,tag:kKfbdRqCqeHpqhUdN0vzvQ==,type:str]
  - ENC[AES256_GCM,data:ss9vDC7QQ3Vc,iv:N3xaGbtarjvKbhYqHAcNPf+HkUz+3lkk6RE/GjBwwGc=,tag:5jkxEHpClQsel50OONdwLQ==,type:comment]
  - ENC[AES256_GCM,data:5GeI4dD6m7aodZg=,iv:p9iMbiygbn1CF2EA4OH6hQcR2njVLL1xrxNRJ/1Kzw0=,tag:BW2cYnazdL2tFFU+mwC6gA==,type:str]
  - ENC[AES256_GCM,data:/v2Q01ZnpW94NQp4nb3AEbdaHylHRhFyzQ==,iv:9V5BxbPrlP2uHrRZFCKx+UzWiufMN5KmfWogxx5kTbE=,tag:91Bx9gWiaoamk10o+jz5Gw==,type:str]
  - ENC[AES256_GCM,data:A+p8yH/JrZVxehJsWQ==,iv:Fz02tW0Hft9dtLQFhUJMDDj+Z0hD4qR7NDEcpv+bgrc=,tag:/nZq2ZiXC/86njSZNaZ5Rw==,type:str]
  - ENC[AES256_GCM,data:NP0HdYW+V5p2,iv:9SSz3aqWkgzNIq10c4ylbpkIgqEP7HTPUyxxkstYEh0=,tag:KLov8ZfONlKKbZdZrHinEQ==,type:comment]
  - ENC[AES256_GCM,data:ywjwXa40tdHN4gDaFVjXYe/wP33m6b+yS1EtBkQ=,iv:YP6l5VLUYXeCNC1sOWgTKY6tI8GkkSZQR0Ew+IT1Y9c=,tag:Z+60i8cqoc+bDDyZJDcqXQ==,type:str]
  - ENC[AES256_GCM,data:ZPvKan0b3g5fqTGwyCmwQ1yIHgUefBJMm6cPtO4R,iv:J2eJl8M+psbgvDI6+AZl/hSH7+E6jTgZ4EGClWWWVZ4=,tag:FcoxjKUl2bKgK6XrrQhD5w==,type:str]
  - ENC[AES256_GCM,data:uhzB9u5UcQOmDLCsx39DgR1se0mA,iv:mr0aTQIuBGy8sNi2CcprNfcsZrH+tcJOH4qti+47D+U=,tag:kYTt/06KKjzSzTMVLe/zLA==,type:str]
  - ENC[AES256_GCM,data:6Aysk5SftjZ6nyoeJ0FS2MBAVlpzhw==,iv:pSiAWW76uxOIcBsaGkpXTvcC6yg0h+pj/qk4kOF3HjQ=,tag:EWiCaTx2TrPslrrWvQqX6A==,type:str]
  - ENC[AES256_GCM,data:nGdF5hWl7SKnkP5KSP8hSrQw4Q==,iv:LHz9+ZvxnkNVJroU3jIy0ayrHtJz9aICCZhvtSKQkRI=,tag:yp/CUUXD3SXB169/1KXRZw==,type:str]
  - ENC[AES256_GCM,data:A6OwtuLCCw==,iv:U92rkKsN0KXXU2KJMFzcrH8+ldclFUsvHDRY9jC+VWI=,tag:V5UVpJsKQva0PUsxM2se1g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hae0mml9ktpyjpmkcfahpzhk2xuckyn2gnw8tr3a6y6yz8gv9qyqr65n9h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd0lKK3picHpIOUU0Um53
        aFg4NVMzNjhwZjl1YTZVVHF1MlRodStjdmxVCnJiWFlxamg0UTNJaHliQnAxTE1J
        ZmxwMUlrRW5vcE1KSmpRMWZ4c05DK2MKLS0tIG9JeTBRUkpIZ2U1RUNsNGYxV1Rj
        TENkR1ZXYmdVS3VkekFaOWRPV1JFK1EKB+ftzNsnOT/6yVQ65Rmrnx0yPqOcVXnK
        FSpH+jRcphvOtegyV4HHWaVbZvlzAnHrnCnQzH8L2ddsiGR+ltZLDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-28T03:28:32Z"
  mac: ENC[AES256_GCM,data:obKj/JT52K/cW9E5Ej+973RgN3umXyaQqRTz2GphHjkWnsTUXDcnL51LQNDnWjFmQ39lrrZlTskI54YEfn50TP5O3F6GNlK92ufzikFQU99mWI6pwwHrD581Bs8PYUow1R06pR+5uWGif1mgwDuhLGL7yZJa4FEuJLSpPGC/Wdg=,iv:MIGaQsyWPsDom6tnE9R929cg4XYtXDgVESfGp8DFh1I=,tag:/TmvJ/urSq9MLrKck93MGQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
